Repository masters2023-project-team05-second-hand/second-hand-max-be-b, pull requests merged in 2023-09, with the labels that each got.

#28 [feat]: 상품 등록 기능 구현
  be/build.gradle
  be/src/main/java/kr/codesquad/secondhand/api/member/repository/MemberRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/member/repository/MemberRepositoryImpl.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/config/S3Config.java
  be/src/main/java/kr/codesquad/secondhand/api/product/controller/ProductController.java
  be/src/main/java/kr/codesquad/secondhand/api/product/domain/Image.java
  be/src/main/java/kr/codesquad/secondhand/api/product/domain/Product.java
  be/src/main/java/kr/codesquad/secondhand/api/product/domain/ProductStatus.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductCreateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductCreateResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/repository/ImageRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/product/repository/ProductRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/product/repository/StatusRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductService.java
  be/src/main/resources/application-s3.yml
  be/src/main/resources/application.yml
Labels: ✨ feat

#32 [feat]: 상품 수정 기능 구현
  be/src/main/java/kr/codesquad/secondhand/api/product/controller/ProductController.java
  be/src/main/java/kr/codesquad/secondhand/api/product/domain/Product.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductModifyRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/product/repository/ImageRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ImageService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductService.java
  be/src/main/resources/application-prodDB.yml
  be/src/main/resources/application.yml
Labels: ✨ feat

#38 [chore] Production 환경 CI/CD 스크립트 작성
  .github/workflows/auto-deploy.yml
  be/Dockerfile
  docker-compose.yml
  fe/Dockerfile
  fe/nginx.conf
Labels: 🔧 chore

#39 [chore] oauth yml파일 prod stage 분리
  be/src/main/resources/application-oauth2-prod.yml
  be/src/main/resources/application-oauth2-stage.yml
  be/src/main/resources/application.yml
Labels: 🔧 chore

#40 feat: 모든 동네 목록 조회 기능 구현 + 로그인 응답 수정
  be/src/main/java/kr/codesquad/secondhand/api/member/controller/MemberController.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/AddressSliceResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/MemberAddressResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/MemberProfileResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/OAuthSignInResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/member/repository/AddressRepositoryImpl.java
  be/src/main/java/kr/codesquad/secondhand/api/member/repository/MemberRepositoryImpl.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/AddressService.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberService.java
  be/src/main/java/kr/codesquad/secondhand/api/oauth/domain/OAuthAttributes.java
Labels: ✨ feat

#41 [feat] 내 동네 수정, 마지막 동네 설정 기능 구현
  be/src/main/java/kr/codesquad/secondhand/api/member/controller/MemberController.java
  be/src/main/java/kr/codesquad/secondhand/api/member/domain/MemberAddress.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/AddressSliceResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/LastVisitedUpdateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/MemberAddressModifyRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/MemberAddressResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/member/repository/AddressRepositoryImpl.java
  be/src/main/java/kr/codesquad/secondhand/api/member/repository/MemberAddressRepositoryImpl.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/AddressService.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberService.java
Labels: ✨ feat

#42 [feat] 상품 개별 조회 기능 구현(스탯 제외)
  be/.gitignore
  be/src/main/java/kr/codesquad/secondhand/api/product/controller/ProductController.java
  be/src/main/java/kr/codesquad/secondhand/api/product/domain/Product.java
  be/src/main/java/kr/codesquad/secondhand/api/product/domain/ProductImage.java
  be/src/main/java/kr/codesquad/secondhand/api/product/domain/ProductStatus.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductReadResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/repository/ImageRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ImageService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/StatusService.java
Labels: ✨ feat

#44 [feat] 상품 삭제 기능 구현
  be/src/main/java/kr/codesquad/secondhand/api/product/controller/ProductController.java
  be/src/main/java/kr/codesquad/secondhand/api/product/repository/ImageRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ImageService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductService.java
Labels: ✨ feat

#45 feat: 상품 상태 변경 기능 구현
  be/src/main/java/kr/codesquad/secondhand/api/product/controller/ProductController.java
  be/src/main/java/kr/codesquad/secondhand/api/product/domain/Product.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductStatusUpdateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductService.java
Labels: ✨ feat

#46 [refactor] 1차 리팩토링
  be/src/main/java/kr/codesquad/secondhand/api/address/controller/AddressController.java
  be/src/main/java/kr/codesquad/secondhand/api/address/domain/Address.java
  be/src/main/java/kr/codesquad/secondhand/api/address/repository/AddressRepositoryImpl.java
  be/src/main/java/kr/codesquad/secondhand/api/address/service/AddressService.java
  be/src/main/java/kr/codesquad/secondhand/api/category/controller/CategoryController.java
  be/src/main/java/kr/codesquad/secondhand/api/category/domain/Category.java
  be/src/main/java/kr/codesquad/secondhand/api/category/dto/CategoriesReadResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/category/dto/CategoryResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/category/repository/CategoryRepositoryImpl.java
  be/src/main/java/kr/codesquad/secondhand/api/category/service/CategoryService.java
  be/src/main/java/kr/codesquad/secondhand/api/member/controller/MemberController.java
  be/src/main/java/kr/codesquad/secondhand/api/member/domain/Member.java
  be/src/main/java/kr/codesquad/secondhand/api/member/domain/MemberAddress.java
  be/src/main/java/kr/codesquad/secondhand/api/member/domain/SignInType.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/LastVisitedUpdateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/MemberAddressModifyRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/request/LastVisitedUpdateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/request/MemberAddressUpdateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/request/OAuthSignInRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/response/AddressSliceResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/response/MemberAddressResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/response/MemberProfileResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/response/OAuthSignInResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/member/repository/SignInTypeRepositoryImpl.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/AddressService.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberAddressService.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberService.java
  be/src/main/java/kr/codesquad/secondhand/api/oauth/domain/OAuthAttributes.java
  be/src/main/java/kr/codesquad/secondhand/api/oauth/domain/OAuthProfile.java
  be/src/main/java/kr/codesquad/secondhand/api/product/controller/ProductController.java
  be/src/main/java/kr/codesquad/secondhand/api/product/domain/Product.java
  be/src/main/java/kr/codesquad/secondhand/api/product/domain/ProductStatus.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductCreateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductModifyRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductReadResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductStatusUpdateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/product/repository/StatusRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ImageService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/StatusService.java
Labels: ♻️ refactor

#53 [feat] member, oauth, category의 기본적인 예외 처리
  be/src/main/java/kr/codesquad/secondhand/api/category/domain/Category.java
  be/src/main/java/kr/codesquad/secondhand/api/category/exception/CategoryException.java
  be/src/main/java/kr/codesquad/secondhand/api/category/exception/InvalidCategoryIdException.java
  be/src/main/java/kr/codesquad/secondhand/api/member/exception/InvalidMemberAddressIdException.java
  be/src/main/java/kr/codesquad/secondhand/api/member/exception/MemberAddressException.java
  be/src/main/java/kr/codesquad/secondhand/api/member/exception/MemberException.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberAddressService.java
  be/src/main/java/kr/codesquad/secondhand/api/oauth/domain/OAuthAttributes.java
  be/src/main/java/kr/codesquad/secondhand/api/oauth/domain/OAuthProfile.java
  be/src/main/java/kr/codesquad/secondhand/api/oauth/exception/InvalidOauthProviderNameException.java
  be/src/main/java/kr/codesquad/secondhand/api/oauth/exception/OAuthException.java
  be/src/main/java/kr/codesquad/secondhand/global/exception/CustomException.java
  be/src/main/java/kr/codesquad/secondhand/global/exception/ErrorResponseEntity.java
  be/src/main/java/kr/codesquad/secondhand/global/exception/GlobalExceptionHandler.java
Labels: ✨ feat

#54 [feat] Redis로 상품 조회수, 관심 기능 구현
  be/build.gradle
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductReadResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/repository/StatRedisRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/StatService.java
  be/src/main/java/kr/codesquad/secondhand/global/config/RedisConfig.java
  be/src/main/resources/application.yml
Labels: ✨ feat

#57 [refactor] product 도메인 리팩토링
  be/src/main/java/kr/codesquad/secondhand/api/product/controller/ProductController.java
  be/src/main/java/kr/codesquad/secondhand/api/product/domain/Product.java
  be/src/main/java/kr/codesquad/secondhand/api/product/domain/ProductImage.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductCreateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductCreateResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductUpdateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/product/exception/ImageUploadFailedException.java
  be/src/main/java/kr/codesquad/secondhand/api/product/exception/ProductException.java
  be/src/main/java/kr/codesquad/secondhand/api/product/exception/ProductImageException.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ImageService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductService.java
Labels: ♻️ refactor

#60 [feat] Redis 설정 파일 추가 및 Stage 배포 스크립트 수정
  be/deploy.sh
  be/src/main/java/kr/codesquad/secondhand/api/product/repository/StatRedisRepository.java
  be/src/main/java/kr/codesquad/secondhand/global/config/RedisConfig.java
  be/src/main/resources/application-db-prod.yml
  be/src/main/resources/application-db-stage.yml
  be/src/main/resources/application-redis-stage.yml
  be/src/main/resources/application.yml
Labels: 🔧 chore

#62 feat: 회원 정보 조회, 회원 동네 정보 조회 기능 구현
  be/src/main/java/kr/codesquad/secondhand/api/member/controller/MemberController.java
  be/src/main/java/kr/codesquad/secondhand/api/member/repository/JpaMemberRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/member/repository/MemberRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/member/repository/MemberRepositoryImpl.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberAddressService.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberService.java
Labels: ✨ feat

#63 [refactor] yml 분리 및 deploy 수정
  be/deploy.sh
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ImageService.java
  be/src/main/resources/application-s3-prod.yml
  be/src/main/resources/application-s3-stage.yml
  be/src/main/resources/application-s3.yml
  be/src/main/resources/application.yml
Labels: ♻️ refactor

#69 [feat]: 상품 상세 조회 시 address, category 래핑 추가
  be/src/main/java/kr/codesquad/secondhand/api/category/controller/CategoryController.java
  be/src/main/java/kr/codesquad/secondhand/api/category/dto/CategoriesReadResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/category/dto/CategoryReadResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/category/service/CategoryService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductReadResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductFacadeService.java
Labels: ✨ feat

#72 [chore] Stage 환경 Github Actions 스크립트 작성 및 기존 스크립트 수정
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-stage.yml
Labels: 🔧 chore

#71 [fix] 상품 수정 시 새로운 이미지 , 삭제된 이미지 NullPointer 에러 해결
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ImageService.java
Labels: ✨ feat

#74 ✨3주차 스프린트 배포
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-stage.yml
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ImageService.java
Labels: ✨ feat, 🔧 chore, ♻️ refactor

#81 [feat] 인가 filter 기능 구현
  be/src/main/java/kr/codesquad/secondhand/api/jwt/exception/JwtExceptionType.java
  be/src/main/java/kr/codesquad/secondhand/api/jwt/exception/TokenNotFoundException.java
  be/src/main/java/kr/codesquad/secondhand/api/jwt/util/JwtProvider.java
  be/src/main/java/kr/codesquad/secondhand/api/member/controller/MemberController.java
  be/src/main/java/kr/codesquad/secondhand/api/product/controller/ProductController.java
  be/src/main/java/kr/codesquad/secondhand/global/config/FilterConfig.java
  be/src/main/java/kr/codesquad/secondhand/global/filter/AuthorizationFilter.java
  be/src/main/java/kr/codesquad/secondhand/global/util/HttpAuthorizationUtils.java
Labels: ✨ feat

#85 [refactor] 3주차 pr 리뷰 내용 반영
  be/src/main/java/kr/codesquad/secondhand/api/category/dto/CategoryReadResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/category/service/CategoryService.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberAddressService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/StatService.java
Labels: ♻️ refactor

#83 [feat] request dto 유효성 검증 기능 구현
  be/build.gradle
  be/src/main/java/kr/codesquad/secondhand/api/member/controller/MemberController.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/request/MemberAddressUpdateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/request/OAuthSignInRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/product/controller/ProductController.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductCreateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductStatusUpdateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductUpdateRequest.java
  be/src/main/java/kr/codesquad/secondhand/global/exception/ErrorResponseEntity.java
  be/src/main/java/kr/codesquad/secondhand/global/exception/GlobalExceptionHandler.java
Labels: ✨ feat

#92 [feat] 로그아웃 기능 구현
  be/src/main/java/kr/codesquad/secondhand/api/jwt/domain/MemberRefreshToken.java
  be/src/main/java/kr/codesquad/secondhand/api/jwt/exception/BlackListedAccessTokenException.java
  be/src/main/java/kr/codesquad/secondhand/api/jwt/exception/JwtExceptionType.java
  be/src/main/java/kr/codesquad/secondhand/api/jwt/repository/TokenRedisRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/jwt/service/JwtService.java
  be/src/main/java/kr/codesquad/secondhand/api/jwt/util/JwtProvider.java
  be/src/main/java/kr/codesquad/secondhand/api/member/controller/MemberController.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/request/SignOutRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/member/exception/InvalidRefreshTokenException.java
  be/src/main/java/kr/codesquad/secondhand/api/member/exception/NotSignedInException.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/global/config/FilterConfig.java
  be/src/main/java/kr/codesquad/secondhand/global/filter/AuthorizationFilter.java
  be/src/main/java/kr/codesquad/secondhand/global/util/HttpAuthorizationUtils.java
Labels: ✨ feat

#91 [feat] 프로필 이미지 수정
  be/src/main/java/kr/codesquad/secondhand/api/member/controller/MemberController.java
  be/src/main/java/kr/codesquad/secondhand/api/member/domain/Member.java
  be/src/main/java/kr/codesquad/secondhand/api/member/domain/MemberAddress.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/request/MemberRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/response/MemberResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/response/OAuthSignInResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/member/exception/InvalidMemberIdException.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberAddressService.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ImageService.java
Labels: ✨ feat

#94 [feat] 닉네임 수정 기능
  be/src/main/java/kr/codesquad/secondhand/api/member/controller/MemberController.java
  be/src/main/java/kr/codesquad/secondhand/api/member/domain/Member.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/MemberProfileImgUpdateDto.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/request/MemberNicknameUpdateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/request/MemberRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/response/MemberResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberService.java
Labels: ✨ feat

#96 [feat] 상품 목록 조회 환경 구성
  be/src/main/java/kr/codesquad/secondhand/api/product/domain/ProductStats.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductReadResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductSlicesResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductStatsResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/repository/StatRedisRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/StatService.java
  be/src/main/java/kr/codesquad/secondhand/global/filter/AuthorizationFilter.java
Labels: ✨ feat, ♻️ refactor

#98 [feat] 판매 목록 조회 기능 구현
  be/src/main/java/kr/codesquad/secondhand/api/address/controller/AddressController.java
  be/src/main/java/kr/codesquad/secondhand/api/member/controller/MemberController.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberProductFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductSlicesResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/repository/ProductRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/product/repository/StatRedisRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/StatService.java
Labels: ✨ feat

#102 [feat] 관심 목록 조회 기능 구현
  be/src/main/java/kr/codesquad/secondhand/api/category/domain/Category.java
  be/src/main/java/kr/codesquad/secondhand/api/category/dto/CategorySummaryResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/member/controller/MemberController.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/MemberProfileImgUpdateDto.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberProductFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/repository/ProductRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/product/repository/StatRedisRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/StatService.java
Labels: ✨ feat

#105 [feat] 메인 페이지 상품 목록 조회 기능 구현
  be/src/main/java/kr/codesquad/secondhand/api/member/controller/MemberController.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberProductFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/controller/ProductController.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/request/ProductCreateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/request/ProductStatusUpdateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/request/ProductUpdateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/response/ProductCreateResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/response/ProductReadResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/response/ProductSlicesResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/response/ProductStatsResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/repository/ProductRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductService.java
  be/src/main/java/kr/codesquad/secondhand/global/filter/AuthorizationFilter.java
Labels: ✨ feat

#106 [feat] API 수정 사항 반영 및 버그 수정
  be/src/main/java/kr/codesquad/secondhand/api/member/controller/MemberController.java
  be/src/main/java/kr/codesquad/secondhand/api/member/domain/MemberAddress.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/ReissueAccessTokenDto.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/response/MemberAddressResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/response/MemberProfileResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/member/repository/MemberAddressRepositoryImpl.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberAddressService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/controller/ProductController.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductStatusesInfoResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/request/ProductUpdateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/response/ProductReadResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ImageService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductService.java
Labels: ✨ feat

#109 [refactor] address, category, jwt 도메인 리팩토링
  be/src/main/java/kr/codesquad/secondhand/api/address/controller/AddressController.java
  be/src/main/java/kr/codesquad/secondhand/api/address/dto/AddressSliceResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/address/service/AddressService.java
  be/src/main/java/kr/codesquad/secondhand/api/category/dto/CategoryReadResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/category/dto/CategorySummaryResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/category/exception/CategoryException.java
  be/src/main/java/kr/codesquad/secondhand/api/jwt/domain/Jwt.java
  be/src/main/java/kr/codesquad/secondhand/api/jwt/domain/MemberRefreshToken.java
Labels: ♻️ refactor

#112 [feat] 관심 상품 crud 기능 구현
  be/src/main/java/kr/codesquad/secondhand/api/member/controller/MemberController.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/request/WishProductRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/response/ProductWishStatusResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberProductFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/StatService.java
Labels: ✨ feat

#114 [feat] 기타 api 수정사항 구현
  be/src/main/java/kr/codesquad/secondhand/api/category/dto/CategoryReadResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/category/dto/CategorySummaryResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/controller/ProductController.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/response/ProductReadResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ImageService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/StatService.java
  be/src/main/java/kr/codesquad/secondhand/global/filter/AuthorizationFilter.java
  be/src/main/java/kr/codesquad/secondhand/global/filter/CorsFilter.java
  be/src/main/java/kr/codesquad/secondhand/global/util/HttpAuthorizationUtils.java
Labels: ✨ feat

#117 [refactor] 레디스 스탯 리팩토링, Product 패키지 단순 리팩토링
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberProductFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/controller/ProductController.java
  be/src/main/java/kr/codesquad/secondhand/api/product/domain/Product.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/response/ProductReadResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/repository/StatRedisRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/StatService.java
  be/src/main/java/kr/codesquad/secondhand/global/filter/AuthorizationFilter.java
Labels: ♻️ refactor

#126 [test] 테스트 컨테이너 환경 구축
  be/build.gradle
  be/src/main/java/kr/codesquad/secondhand/api/image/config/S3Config.java
  be/src/main/java/kr/codesquad/secondhand/api/image/excpetion/ImageUploadFailedException.java
  be/src/main/java/kr/codesquad/secondhand/api/image/repository/ImageRepository.java
  be/src/main/java/kr/codesquad/secondhand/api/image/service/ImageService.java
  be/src/main/java/kr/codesquad/secondhand/api/image/util/ImageUploader.java
  be/src/main/java/kr/codesquad/secondhand/api/image/util/S3ImageUploader.java
  be/src/main/java/kr/codesquad/secondhand/api/member/service/MemberFacadeService.java
  be/src/main/java/kr/codesquad/secondhand/api/product/service/ProductFacadeService.java
  be/src/main/resources/application-test.yml
  be/src/main/resources/application.yml
  be/src/test/java/kr/codesquad/secondhand/api/address/integration/AddressTest.java
  be/src/test/java/kr/codesquad/secondhand/config/TestContainers.java
  be/src/test/java/kr/codesquad/secondhand/fixture/ProductImageFixtureFactory.java
  be/src/test/java/kr/codesquad/secondhand/util/IntegrationTest.java
  be/src/test/java/kr/codesquad/secondhand/util/TestImageUploader.java
  be/src/test/resources/application.properties
  be/src/test/resources/data.sql
  be/src/test/resources/schema.sql
Labels: ✅ test

#130 [test] 인증/인가 테스트 코드 작성
  be/build.gradle
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/ReissueAccessTokenDto.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/request/SignOutRequest.java
  be/src/test/java/kr/codesquad/secondhand/acceptance/AuthAcceptanceTest.java
  be/src/test/java/kr/codesquad/secondhand/fixture/MemberFixture.java
  be/src/test/java/kr/codesquad/secondhand/step/AuthStep.java
  be/src/test/java/kr/codesquad/secondhand/util/AcceptanceTest.java
Labels: ✅ test

#134 [test] 메뉴 조회 테스트 코드 작성
  be/src/main/java/kr/codesquad/secondhand/api/category/dto/CategoryReadResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/product/dto/ProductStatusesInfoResponse.java
  be/src/test/java/kr/codesquad/secondhand/acceptance/CategoryAcceptanceTest.java
  be/src/test/java/kr/codesquad/secondhand/acceptance/StatusAcceptanceTest.java
  be/src/test/java/kr/codesquad/secondhand/step/CategoryStep.java
  be/src/test/java/kr/codesquad/secondhand/step/StatusStep.java
Labels: ✅ test

#136 [test] 회원 도메인 관련 테스트 코드 작성
  be/src/main/java/kr/codesquad/secondhand/api/address/domain/Address.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/request/MemberAddressUpdateRequest.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/response/MemberAddressResponse.java
  be/src/main/java/kr/codesquad/secondhand/api/member/dto/response/MemberProfileResponse.java
  be/src/test/java/kr/codesquad/secondhand/acceptance/MemberAcceptanceTest.java
  be/src/test/java/kr/codesquad/secondhand/fixture/AddressFixture.java
  be/src/test/java/kr/codesquad/secondhand/step/MemberSteps.java
  be/src/test/resources/data.sql
Labels: ✅ test
